package com.example.mainnegarestan.model.product

class Collage (
    var id: Long,
    var tissueType: String? = "",
    var khabType: String? = "",
    var tarType: String? = "",
    var poodType: String? = "",
    var product_id : Long? = null,
    var code : String? ="",
    var weight : String? ="",
    var dimensions : String? ="",
    var size : String? ="",
    var color : String? ="",
    var shape : String? ="",
    var image : String? ="",
    var attribute : String? ="",
    var visitCount : Long? = null,
    var addDate : String? ="",
    var category : String? ="",
    var property : String? ="",
    var description : String? ="",
    var price : String? ="",
    var quantity : String? ="",
        )