package com.example.mainnegarestan.model.product

data class Moquette(
    var id : Long,
    var thickNess: String? ="",
    var design: String? = "",
    var tissueType: String? = "",
    var threadType: String? = "",
    var layers: Long? = null,
    var product_id : Long? = null,
    var code : String? ="",
    var weight : String? ="",
    var dimensions : String? ="",
    var size : String? ="",
    var color : String? ="",
    var shape : String? ="",
    var image : String? ="",
    var attribute : String? ="",
    var visitCount : Long? = null,
    var addDate : String? ="",
    var category : String? ="",
    var property : String? ="",
    var description : String? ="",
    var price : String? ="",
    var quantity : String? ="",
)
